//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace callWebService.myServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myServiceReference.IhashSignSVC")]
    public interface IhashSignSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhashSignSVC/SignandReturn", ReplyAction="http://tempuri.org/IhashSignSVC/SignandReturnResponse")]
        byte[] SignandReturn(string myAlias, byte[] myHash, string myPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IhashSignSVC/SignandReturn", ReplyAction="http://tempuri.org/IhashSignSVC/SignandReturnResponse")]
        System.Threading.Tasks.Task<byte[]> SignandReturnAsync(string myAlias, byte[] myHash, string myPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IhashSignSVCChannel : callWebService.myServiceReference.IhashSignSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IhashSignSVCClient : System.ServiceModel.ClientBase<callWebService.myServiceReference.IhashSignSVC>, callWebService.myServiceReference.IhashSignSVC {
        
        public IhashSignSVCClient() {
        }
        
        public IhashSignSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IhashSignSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IhashSignSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IhashSignSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] SignandReturn(string myAlias, byte[] myHash, string myPassword) {
            return base.Channel.SignandReturn(myAlias, myHash, myPassword);
        }
        
        public System.Threading.Tasks.Task<byte[]> SignandReturnAsync(string myAlias, byte[] myHash, string myPassword) {
            return base.Channel.SignandReturnAsync(myAlias, myHash, myPassword);
        }
    }
}
